schema_version = "1.0.0"
id = "stablegen"
version = "0.0.1"
name = "StableGen"
tagline = "Seamless AI Multi-View Texturing Powered by SDXL"
maintainer = "Ondrej Sakala <sakalaondrej@gmail.com>"
type = "add-on"
blender_version_min = "4.2.0"

website = "https://github.com/sakalond/StableGen"

tags = ["object", "texturing", "texture", "stable diffusion", "AI", "generative art", "render"]

license = ["SPDX:GPL-3.0-or-later"]

copyright = [
"2024 Ondrej Sakala",
]
platforms = ["windows-x64", "linux-x64"]

[permissions]
network = "Connects to ComfyUI server for AI texture generation"
files = "Load AI models and save generated textures and intermediate images to disk"